# Data Acquisition - Part A

In [11]:
import pandas as pd

# Task 1

In [75]:
Population=pd.read_csv('/content/population.csv')
Population

           country  population
0    United States  1278642419
1            China   792846414
2            India  1001406378
3            Japan  1206263687
4          Germany   428734972
5           Russia   420968276
6           Brazil   675094950
7   United Kingdom   674991378
8           France   434389014
9            Italy   254467210
10          Canada  1438267572
11       Australia   439285667
12     South Korea   618608295
13           Spain   898664919
14          Mexico   653061058
15       Indonesia    93409749
16          Turkey   247285876
17    Saudi Arabia   958477463
18       Argentina  1432830251
19    South Africa   916989541

In [16]:
Population.head()

         country  population
0  United States  1278642419
1          China   792846414
2          India  1001406378
3          Japan  1206263687
4        Germany   428734972

In [17]:
Population.shape

(20, 2)

In [18]:
Population.dtypes

country       object
population     int64
dtype: object

In [19]:
Population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     20 non-null     object
 1   population  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

# Task 2

In [13]:
gdp=pd.read_excel('/content/gdp.xlsx')
gdp

           Country             GDP
0    United States  10450436373455
1            China   5086547998939
2            India  14540718118693
3            Japan  12473835857216
4          Germany   2038442396490
5           Russia  10987125474745
6           Brazil   8793052816619
7   United Kingdom  11799848684255
8           France   7758669752269
9            Italy  12907234326850
10          Canada   8158351525190
11       Australia   5444267975247
12     South Korea   6562909541266
13           Spain  15275513099842
14          Mexico   2775281278756
15       Indonesia  12404144955318
16          Turkey   2581127745611
17    Saudi Arabia   8855399647233
18       Argentina   8767336567320
19    South Africa   3328747361982

In [20]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [22]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [25]:
gdp.describe()

                GDP
count  2.000000e+01
mean   8.549450e+12
std    4.076091e+12
min    2.038442e+12
25%    5.354838e+12
50%    8.780195e+12
75%    1.195092e+13
max    1.527551e+13

# Task 3

In [15]:
internet_users=pd.read_json('/content/internet_users.json')
internet_users

           country  internet_users
0    United States       745595490
1            China       685275917
2            India       606850704
3            Japan      1112451555
4          Germany       246827121
5           Russia       162156967
6           Brazil        24027075
7   United Kingdom       266047041
8           France       216417853
9            Italy        87191493
10          Canada       894102645
11       Australia       201619113
12     South Korea       291770691
13           Spain       794943861
14          Mexico       135489564
15       Indonesia         4584702
16          Turkey       128924625
17    Saudi Arabia       108944665
18       Argentina       421477197
19    South Africa       739194223

# Task 4

In [14]:
literacy_rate=pd.read_xml('/content/literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           72.7
1            China           82.2
2            India           80.3
3            Japan           97.5
4          Germany           92.9
5           Russia           89.1
6           Brazil           81.0
7   United Kingdom           82.9
8           France           97.6
9            Italy           83.7
10          Canada           70.8
11       Australia           71.6
12     South Korea           66.4
13           Spain           60.6
14          Mexico           76.5
15       Indonesia           75.4
16          Turkey           71.4
17    Saudi Arabia           60.5
18       Argentina           67.8
19    South Africa           87.7

# Part B -Task 5

In [27]:
Population.shape[0]

20

In [28]:
Population.shape[1]

2

In [37]:
Population.shape

(20, 2)

In [38]:
Population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     20 non-null     object
 1   population  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [39]:
Population.describe()

         population
count  2.000000e+01
mean   7.432343e+08
std    3.947080e+08
min    9.340975e+07
25%    4.329755e+08
50%    6.750432e+08
75%    9.692097e+08
max    1.438268e+09

In [31]:
Population.columns

Index(['country', 'population'], dtype='object')

In [32]:
Population.dtypes

country       object
population     int64
dtype: object

In [33]:
Population.isnull().sum()

country       0
population    0
dtype: int64

In [34]:
Population.duplicated().sum()

np.int64(0)

In [35]:
gdp.shape[0]

20

In [36]:
gdp.shape[1]

2

In [40]:
gdp.shape

(20, 2)

In [41]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [43]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [44]:
gdp.isnull().sum()

Country    0
GDP        0
dtype: int64

In [45]:
gdp.duplicated().sum()

np.int64(0)

In [46]:
internet_users.shape

(20, 2)

In [48]:
internet_users.shape[1]

2

In [51]:
internet_users.shape[0]

20

In [52]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [54]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [55]:
internet_users.isnull().sum()

country           0
internet_users    0
dtype: int64

In [57]:
internet_users.duplicated().sum()

np.int64(0)

In [59]:
internet_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         20 non-null     object
 1   internet_users  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [60]:
literacy_rate.shape

(20, 2)

In [62]:
literacy_rate.shape[0]

20

In [63]:
literacy_rate.shape[1]

2

In [64]:
literacy_rate.dtypes

name              object
literacy_rate    float64
dtype: object

In [65]:
literacy_rate.columns

Index(['name', 'literacy_rate'], dtype='object')

In [66]:
literacy_rate.isnull().sum()

name             0
literacy_rate    0
dtype: int64

In [67]:
literacy_rate.duplicated().sum()

np.int64(0)

In [68]:
literacy_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           20 non-null     object
 1   literacy_rate  20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 452.0+ bytes

# Task 6

In [70]:
gdp.rename(columns={'Country':'country'}, inplace=True)
gdp.head()

         country             GDP
0  United States  10450436373455
1          China   5086547998939
2          India  14540718118693
3          Japan  12473835857216
4        Germany   2038442396490

In [73]:
literacy_rate.rename(columns={'name':'country'},inplace=True)
literacy_rate.head()

         country  literacy_rate
0  United States           72.7
1          China           82.2
2          India           80.3
3          Japan           97.5
4        Germany           92.9

# Task 7

In [78]:
Population["population"] = pd.to_numeric(Population["population"])

gdp["GDP"] = pd.to_numeric(gdp["GDP"])

internet_users["internet_users"] = pd.to_numeric(internet_users["internet_users"])

literacy_rate["literacy_rate"] = pd.to_numeric(literacy_rate["literacy_rate"])

In [80]:
Population.dtypes

country           object
literacy_rate    float64
dtype: object

All datas are in integer types

# Task 8

In [82]:
df = Population.merge(gdp, on='country', how='inner')
df = df.merge(internet_users, on='country', how='inner')
df = df.merge(literacy_rate, on='country', how='inner')

df.head()

         country  population             GDP  internet_users  literacy_rate
0  United States  1278642419  10450436373455       745595490           72.7
1          China   792846414   5086547998939       685275917           82.2
2          India  1001406378  14540718118693       606850704           80.3
3          Japan  1206263687  12473835857216      1112451555           97.5
4        Germany   428734972   2038442396490       246827121           92.9

# Task 9

In [84]:
df["Internet Penetration (%)"] = round((df["internet_users"] / df["population"]) * 100, 2)
df["GDP Per Capita"] = round(df["GDP"] / df["population"], 2)
df.head()

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,1278642419,10450436373455,745595490,72.7,58.31,8173.07
1,China,792846414,5086547998939,685275917,82.2,86.43,6415.55
2,India,1001406378,14540718118693,606850704,80.3,60.60,14520.30
3,Japan,1206263687,12473835857216,1112451555,97.5,92.22,10340.89
4,Germany,428734972,2038442396490,246827121,92.9,57.57,4754.55

# Task 10

In [85]:
import sqlite3

In [86]:
try:
  conn=sqlite3.connect("country_statistics.db")
  cursor=conn.cursor()
  print("Database created successfully")
except sqlite3.Error as error:
  print("Error connecting to database,e")

Database created successfully

# Task 11

In [89]:
df.to_sql(
    'country_statistics',
    conn,
    if_exists='replace',
    index=False
)

20

In [90]:

pd.read_sql("SELECT * FROM country_statistics LIMIT 5", conn)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,1278642419,10450436373455,745595490,72.7,58.31,8173.07
1,China,792846414,5086547998939,685275917,82.2,86.43,6415.55
2,India,1001406378,14540718118693,606850704,80.3,60.60,14520.30
3,Japan,1206263687,12473835857216,1112451555,97.5,92.22,10340.89
4,Germany,428734972,2038442396490,246827121,92.9,57.57,4754.55

# Part E – Data Analysis Using Pandas

In [91]:
#1,
df.nlargest(5, "GDP")[["country", "GDP"]]

      country             GDP
13      Spain  15275513099842
2       India  14540718118693
9       Italy  12907234326850
3       Japan  12473835857216
15  Indonesia  12404144955318

In [92]:
#2,
df.nlargest(5, "population")[["country", "population"]]

          country  population
10         Canada  1438267572
18      Argentina  1432830251
0   United States  1278642419
3           Japan  1206263687
2           India  1001406378

In [93]:
#3,
round(df["literacy_rate"].mean(), 2)

np.float64(78.43)

In [94]:
#4,
df[df["literacy_rate"] > 90][["country", "literacy_rate"]]

   country  literacy_rate
3    Japan           97.5
4  Germany           92.9
8   France           97.6

In [95]:
#5,
df[df["Internet Penetration (%)"] > 70][["country", "Internet Penetration (%)"]]

         country  Internet Penetration (%)
1          China                     86.43
3          Japan                     92.22
13         Spain                     88.46
19  South Africa                     80.61

In [96]:
#6,
df.nlargest(5, "GDP Per Capita")[["country", "GDP Per Capita"]]

           country  GDP Per Capita
15       Indonesia       132792.83
9            Italy        50722.58
5           Russia        26099.65
8           France        17861.11
7   United Kingdom        17481.48

In [97]:
#7,
df["population"].sum()

np.int64(14864685089)

In [98]:
#8,
round(df["Internet Penetration (%)"].mean(), 2)

np.float64(48.18)

In [99]:
#9,
df.loc[df["internet_users"].idxmax(), ["country", "internet_users"]]

country                Japan
internet_users    1112451555
Name: 3, dtype: object

In [100]:
#10,
df["literacy_rate"].corr(df["Internet Penetration (%)"])

np.float64(0.2352598619210605)

# Part F- Data Analysis Using SQL

In [101]:
#11,
query = """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

     country             GDP
0      Spain  15275513099842
1      India  14540718118693
2      Italy  12907234326850
3      Japan  12473835857216
4  Indonesia  12404144955318

In [102]:
#12,
query = """
SELECT AVG(literacy_rate) AS average_literacy_rate
FROM country_statistics;
"""

pd.read_sql_query(query, conn)

   average_literacy_rate
0                  78.43

In [103]:
#13,
query = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90;
"""

pd.read_sql_query(query, conn)

   country  literacy_rate
0    Japan           97.5
1  Germany           92.9
2   France           97.6

In [105]:
#14,
query = """
SELECT country, "Internet Penetration (%)"
FROM country_statistics
ORDER BY "Internet Penetration (%)" DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

        country  Internet Penetration (%)
0         Japan                     92.22
1         Spain                     88.46
2         China                     86.43
3  South Africa                     80.61
4        Canada                     62.17

In [106]:
#15,
query = """
SELECT SUM(population) AS total_population
FROM country_statistics;
"""

pd.read_sql_query(query, conn)

   total_population
0       14864685089

In [107]:
#16,
query = """
SELECT country, "GDP Per Capita"
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 1;
"""
pd.read_sql_query(query,conn)

     country  GDP Per Capita
0  Indonesia       132792.83

In [108]:
#17,
df.to_csv("country_statistics.csv", index=False)

print("CSV file exported successfully!")

CSV file exported successfully!

In [109]:
#18,
query = """
SELECT country, "GDP Per Capita"
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 10;
"""
pd.read_sql_query(query,conn)

          country  GDP Per Capita
0       Indonesia       132792.83
1           Italy        50722.58
2          Russia        26099.65
3          France        17861.11
4  United Kingdom        17481.48
5           Spain        16998.01
6           India        14520.30
7          Brazil        13024.91
8       Australia        12393.46
9     South Korea        10609.15

# ETL Process Summary

Extracted country-related data from four different sources: CSV,
Excel, JSON, and XML files.

Cleaned the data by checking for missing values, duplicate records, standardizing column names, and converting fields to appropriate numeric data types.

Combined all datasets into a single table and created two additional metrics: Internet Penetration (%) and GDP Per Capita for better analysis.

Loaded the processed dataset into a SQLite database under the table country_statistics for efficient storage and querying.

The analysis highlighted differences in GDP, population, literacy, and internet usage across countries, providing a clear view of their overall development.