In [61]:
#1,
import numpy as np
x= np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [62]:
y=x.reshape(4,10)
y

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
y[:,-1]

array([19, 29, 39, 49])

In [64]:
#2.
x=np.ones((3,3)) * 5
x

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [65]:
y=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
z=(x+y)
z

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [67]:
s=np.multiply(x,y)
s

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

In [68]:
s.T

array([[ 5., 20., 35.],
       [10., 25., 40.],
       [15., 30., 45.]])

In [69]:
#3                                             #np.where() is used for conditional selection or replacement.
import numpy as np
a= np.random.randint(10,100,15)
print("Original:", a)
count = np.sum(a> 50)

a = np.where(a > 50, -1, a)

print("Modified:", a)
print("Count:", count)

Original: [54 51 88 16 70 24 75 13 64 63 84 45 19 62 67]
Modified: [-1 -1 -1 16 -1 24 -1 13 -1 -1 -1 45 19 -1 -1]
Count: 10

In [70]:
#4
b=np.random.rand(5,4)
b

array([[0.67924305, 0.96352987, 0.84269153, 0.00697908],
       [0.84370895, 0.34371608, 0.48548664, 0.7373968 ],
       [0.57618402, 0.01638896, 0.31108137, 0.88803154],
       [0.32551756, 0.22436992, 0.62438228, 0.54215175],
       [0.48834497, 0.07973585, 0.71795499, 0.73026852]])

In [71]:
Row_sum=np.sum(b,axis=1)
print(Row_sum)

[2.49244353 2.41030847 1.79168589 1.7164215  2.01630434]

In [97]:
Max_row = np.argmax(Row_sum)
Max_row

np.int64(0)

In [98]:
Normalized = (b-b.min(axis=1,keepdims=True))/(b.max(axis=1,keepdims =True)-b.min(axis=1,keepdims=True))
Normalized

array([[0.70280008, 1.        , 0.87367285, 0.        ],
       [1.        , 0.        , 0.28354515, 0.78737266],
       [0.64223005, 0.        , 0.33808858, 1.        ],
       [0.25286128, 0.        , 1.        , 0.79443002],
       [0.62811468, 0.        , 0.98107162, 1.        ]])

In [39]:
#5
arr=np.array([1,3,5,3,7,9,1,5,5])
arr

array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [40]:
np.unique(arr)

array([1, 3, 5, 7, 9])

In [41]:
u,c=np.unique(arr,return_counts=True)
print("Duplicate:",u[c>1])

Duplicate: [1 3 5]

In [42]:
#6,
x=np.arange(1,37)
y=x.reshape(6,6)
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [43]:
middle= y[1:5,1:5]          #1:5 rows → row indices 1, 2, 3, 4
                            #1:5 columns → column indices 1, 2, 3, 4
middle

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [44]:
even=middle[middle%2==0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [45]:
#7,
x=np.arange(0,12)
y=x.reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
z=y.reshape(2,6)
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
a=z.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
#8,
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [50]:
s=np.vstack((a,[5,6]))
s

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
y=np.column_stack((s,[7,8,9]))
y

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [52]:
#9,
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.concatenate((a,b,c))
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
e=d.reshape(3,3)
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
diag=np.diag(e) #extract diagonal elements
diag

array([1, 5, 9])

In [55]:
#10,
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
b=a[(a%3==0) |(a%5==0)]
b

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [57]:
len(b)

9

# Pandas

In [75]:
import pandas as pd
df=pd.read_csv("/titanic_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [106]:
#1,
data=df.head(10)
data

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q,Adult
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Child

In [108]:
#2,
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
gender         0
Age            0
SibSp          0
Parch          0
Ticket         0
ticket_fare    0
Cabin          7
Embarked       0
age_group      0
dtype: int64

In [78]:
#,
survival_rate = data.groupby('Sex')['Survived'].mean() * 100

print(survival_rate)

Sex
female    100.0
male        0.0
Name: Survived, dtype: float64

In [79]:
#4,
data["Age"].agg(["mean","median","std"])

mean      28.111111
median    27.000000
std       14.945271
Name: Age, dtype: float64

In [80]:
#5,
data["Pclass"].value_counts()

Pclass
3    6
1    3
2    1
Name: count, dtype: int64

In [129]:
#6,
data[(data['Sex'] == 'female') &
   (data['Age'] < 18) &
   (data['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Child

In [110]:
#7,
data['Age'] = data['Age'].fillna(data['Age'].median())
data['Age'].isna().sum()

/tmp/ipykernel_1425/601149348.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'] = data['Age'].fillna(data['Age'].median())

np.int64(0)

In [135]:
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q,Adult
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Child

In [134]:
#8,
import numpy as np

df['age_group'] = np.where(df['Age'] < 18, 'Child',
                           np.where(df['Age'] <= 60, 'Adult', 'Senior'))

df[['Age','age_group']].head(10)

    Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child

In [140]:
#9,
df.nlargest(5, 'Fare')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult

In [141]:
#10,
df.groupby(['Pclass','Sex'])['Fare'].mean()

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [159]:
#11,
df.rename(columns={'Sex':'gender','Fare':'ticket_fare'}, inplace=True)
df

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

In [153]:

#12,
df.groupby('Pclass')['Survived'].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [160]:
#13,
df.groupby(['Pclass','gender'])['Age'].mean()

Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64