##   Case Study of pandas
1) Import pandas, numpy
2) Load dataset using pd.read_csv()

In [ ]:
import numpy as np
import pandas as pd
df= pd.read_csv("/content/IMDB-Movie-Data.csv")
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

**3) Display: shape, head, column names, datatypes, missing value**

In [ ]:
df.shape    #display shape

(1000, 12)

In [ ]:
df.head()   #display head

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
df.columns   #column names

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [ ]:
df.dtypes #datatypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [ ]:
df.info()        #all information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [ ]:
df.isnull().sum()         #missing value

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

**4) Check and remove duplicates**

In [ ]:
df.duplicated().sum()        #here there is no duplicates

np.int64(0)

**5) Rename columns ("Title" > "Movie_Title")**

In [ ]:
df=df.rename(columns={"Title":"Movie_Title"})
df.columns

Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Genre_Count', 'Profitability', 'Category', 'Score'],
      dtype='object')

**6)Get unique genres**

In [ ]:
df["Genre"].str.split(",").explode().unique()

array(['Action', 'Adventure', 'Sci-Fi', 'Mystery', 'Horror', 'Thriller',
       'Animation', 'Comedy', 'Family', 'Fantasy', 'Drama', 'Music',
       'Biography', 'Romance', 'History', 'Crime', 'Western', 'War',
       'Musical', 'Sport'], dtype=object)

In [ ]:
#Number of Unique Genres
df["Genre"].str.split(",").explode().nunique()

20

**7) Extract number of genres per movie**

In [ ]:
df["Genre_Count"] = df["Genre"].str.count(",") + 1
df[["Movie_Title","Genre_Count"]]

                 Movie_Title  Genre_Count
0    Guardians of the Galaxy            3
1                 Prometheus            3
2                      Split            2
3                       Sing            3
4              Suicide Squad            3
..                       ...          ...
995     Secret in Their Eyes            3
996          Hostel: Part II            1
997   Step Up 2: The Streets            3
998             Search Party            2
999               Nine Lives            3

[1000 rows x 2 columns]

**8) Handle missing values in 'Revenue (Millions)' and 'Metascore**

In [ ]:
#Finding missing values in Revenue and Metascore
df[["Revenue (Millions)","Metascore"]].isnull().sum()

Revenue (Millions)    128
Metascore              64
dtype: int64

In [ ]:
#Filling or handling null values
df["Revenue (Millions)"] = df["Revenue (Millions)"].fillna(df["Revenue (Millions)"].mean())

df["Metascore"] = df["Metascore"].fillna(df["Metascore"].mean())
df

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Genre_Count
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130000,76.0,3
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460000,65.0,3
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120000,62.0,2
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320000,59.0,3
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020000,40.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,82.956376,45.0,3
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540000,46.0,1
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010000,50.0,3
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,82.956376,22.0,2
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640000,11.0,3

In [ ]:
#Finally there is no null values
df[["Revenue (Millions)", "Metascore"]].isnull().sum()

Revenue (Millions)    0
Metascore             0
dtype: int64

**9) Top 5 movies by Rating**

In [ ]:
df.sort_values(by="Rating", ascending=False).head(5)[["Movie_Title", "Rating"]]

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

**10) Movies with highest/lowest revenue**

In [ ]:
#Movies with Highest revenue
df.nlargest(5, "Revenue (Millions)")[["Movie_Title","Revenue (Millions)"]]

                                   Movie_Title  Revenue (Millions)
50  Star Wars: Episode VII - The Force Awakens              936.63
87                                      Avatar              760.51
85                              Jurassic World              652.18
76                                The Avengers              623.28
54                             The Dark Knight              533.32

In [ ]:
#Movies with lowest revenue
df.nsmallest(5, "Revenue (Millions)")[["Movie_Title","Revenue (Millions)"]]

          Movie_Title  Revenue (Millions)
231  A Kind of Murder                0.00
27         Dead Awake                0.01
68          Wakefield                0.01
321          Lovesong                0.01
677       Love, Rosie                0.01

**11) Avg. rating by Director**

In [ ]:
df.groupby("Director")["Rating"].mean()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

**12) Movies per year**

In [ ]:
df.groupby("Year")["Movie_Title"].count()

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: Movie_Title, dtype: int64

**13) Movies with rating > 8 & revenue > 100M**

In [ ]:
df[(df["Rating"] > 8) & (df["Revenue (Millions)"] > 100)][["Movie_Title","Rating","Revenue (Millions)"]]

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

14) **Group by Director: avg Rating, Revenue**

In [ ]:
df.groupby("Director")[["Rating","Revenue (Millions)"]].mean()

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

**15)Group by Year: count, avg Rating**

In [ ]:
df.groupby("Year").agg({"Movie_Title":"count","Rating":"mean"}).reset_index()

    Year  Movie_Title    Rating
0   2006           44  7.125000
1   2007           53  7.133962
2   2008           52  6.784615
3   2009           51  6.960784
4   2010           60  6.826667
5   2011           63  6.838095
6   2012           64  6.925000
7   2013           91  6.812088
8   2014           98  6.837755
9   2015          127  6.602362
10  2016          297  6.436700

**16) Create a new column Profitability:**

     a) Revenue divided by Duration

     b) Find top 10 most profitable movies

In [ ]:
#a,
df["Profitability"] = df["Revenue (Millions)"] / df["Runtime (Minutes)"]
df

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Genre_Count,Profitability
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130000,76.0,3,2.753140
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460000,65.0,3,1.019839
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120000,62.0,2,1.180513
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320000,59.0,3,2.502963
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020000,40.0,3,2.642439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,82.956376,45.0,3,0.747355
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540000,46.0,1,0.186596
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010000,50.0,3,0.591939
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,82.956376,22.0,2,0.892004
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640000,11.0,3,0.225747

In [ ]:
#b,
df.nlargest(10, "Profitability")[["Movie_Title","Profitability"]]

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

**17.Create a column that categorizes movies by rating:**

       a) Rating < 6: Poor

       b) 6 ≤ Rating < 7.5: Average

       c) Rating ≥ 7.5: Excellent

In [ ]:
df["Category"] = np.where(df["Rating"] < 6, "Poor",
                 np.where(df["Rating"] < 7.5, "Average", "Excellent"))

In [ ]:
df[["Movie_Title","Rating","Category"]]

                 Movie_Title  Rating   Category
0    Guardians of the Galaxy     8.1  Excellent
1                 Prometheus     7.0    Average
2                      Split     7.3    Average
3                       Sing     7.2    Average
4              Suicide Squad     6.2    Average
..                       ...     ...        ...
995     Secret in Their Eyes     6.2    Average
996          Hostel: Part II     5.5       Poor
997   Step Up 2: The Streets     6.2    Average
998             Search Party     5.6       Poor
999               Nine Lives     5.3       Poor

[1000 rows x 3 columns]

**18)Create a custom function to score movies based on:**

        i) Apply row['Rating'] * 10 + row['Revenue (Millions)'] as High score

           Apply a function to dataset to assign the score

In [ ]:
def score(row):
    return row["Rating"] * 10 + row["Revenue (Millions)"]

df["Score"] = df.apply(score, axis=1)
df[["Movie_Title","Score"]]

                 Movie_Title       Score
0    Guardians of the Galaxy  414.130000
1                 Prometheus  196.460000
2                      Split  211.120000
3                       Sing  342.320000
4              Suicide Squad  387.020000
..                       ...         ...
995     Secret in Their Eyes  144.956376
996          Hostel: Part II   72.540000
997   Step Up 2: The Streets  120.010000
998             Search Party  138.956376
999               Nine Lives   72.640000

[1000 rows x 2 columns]